[topology]
version = "0.1.0"
generated_at = "2025-12-17T16:46:56Z"
generator = "aps-cli"
generator_version = "0.1.0"

[analysis]
root = "."
languages = ["python", "rust"]
total_files = 1052
total_functions = 9442
total_modules = 609
total_dependencies = 3013
