[topology]
version = "0.1.0"
generated_at = "2025-12-17T22:21:27Z"
generator = "aps-cli"
generator_version = "0.1.0"

[analysis]
root = "."
languages = ["tsx", "python", "typescript", "rust"]
total_files = 881
total_functions = 7134
total_modules = 595
total_dependencies = 182
