// Small framework-free state machines (reducers). Phase agents add:
// day stepper, selection, filters. See CONVENTIONS.md "skyline-core".
export { run } from './machine'
export type { Reducer } from './machine'
export { copyFeedback, COPY_FEEDBACK_MS } from './copyFeedback'
export type { CopyState, CopyEvent } from './copyFeedback'
export { listMoveForKey, moveIndex, typeaheadIndex } from './listNav'
export type { ListMove, ListOrientation } from './listNav'
export { toggleValue, selectAllState } from './selection'
export type { SelectionType } from './selection'
export { clampPage, paginationRange, shownCount } from './pagination'
export type { PageItem } from './pagination'
export { commandScore, filterCommandGroups } from './commandFilter'
export type { CommandFilterItem, CommandFilterGroup } from './commandFilter'
export { dayStepper, initialDayStepper, stepperPosition, stepperKey } from './dayStepper'
export type { DayStepperState, DayStepperEvent } from './dayStepper'
export { gridCursor, gridKey } from './gridCursor'
export type { GridCursorState, GridCursorEvent } from './gridCursor'
export { CHORD_MS, GOTO_KEYS, KEYMAP, KEYMAP_IDLE, keyLabel, keymapGroups, keymapStep, keyToken, sequenceLabel, shortcutFor } from './keymap'
export type { FeedbackMode, KeyAction, KeyBinding, KeyFeature, KeyGroup, KeyInput, KeymapResult, KeymapSection, KeymapState } from './keymap'
