"""Pydantic model for the distributable triggers.json format.

This model defines the schema for trigger definitions embedded in plugin
packages (triggers.json per workflow). It is the source of truth for the
triggers.schema.json file generated by scripts/export_plugin_schemas.py.

Note: This is separate from the domain-level TriggerCondition and TriggerConfig
dataclasses in the github bounded context. Those model runtime trigger behavior
in the aggregate. This model defines the distributable file format that plugin
authors write. The two may intentionally diverge — the domain aggregate may
support fields that aren't exposed in the distributable format, or vice versa.

See ADR-052 for the schema generation strategy.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

UNARY_OPERATORS = frozenset({"not_empty", "is_empty"})
BINARY_OPERATORS = frozenset({"eq", "neq", "contains"})
LIST_OPERATORS = frozenset({"in", "not_in"})


class TriggerConditionSchema(BaseModel):
    """A condition evaluated against the GitHub webhook payload.

    Uses dot-notation paths to traverse nested payloads.

    Examples:
        {"field": "action", "operator": "eq", "value": "opened"}
        {"field": "check_run.conclusion", "operator": "in", "value": ["failure", "timed_out"]}
        {"field": "check_run.pull_requests", "operator": "not_empty"}
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    field: str = Field(
        ...,
        min_length=1,
        description="Dot-notation path into the webhook payload (e.g., 'check_run.conclusion').",
    )
    operator: Literal["eq", "neq", "in", "not_in", "not_empty", "is_empty", "contains"] = Field(
        ...,
        description="Comparison operator. Unary operators (not_empty, is_empty) require no value. "
        "Binary operators (eq, neq, contains) require a scalar value. "
        "List operators (in, not_in) require an array value.",
    )
    value: str | int | bool | list[str] | None = Field(
        default=None,
        description="Expected value. Required for binary/list operators, must be omitted for unary operators.",
    )

    @model_validator(mode="after")
    def _validate_operator_value_consistency(self) -> TriggerConditionSchema:
        op, val = self.operator, self.value
        if op in UNARY_OPERATORS and val is not None:
            msg = f"Unary operator '{op}' must not have a value (got {val!r})."
            raise ValueError(msg)
        if op in LIST_OPERATORS and not isinstance(val, list):
            msg = f"List operator '{op}' requires an array value (got {type(val).__name__})."
            raise ValueError(msg)
        if op in BINARY_OPERATORS and val is None:
            msg = f"Binary operator '{op}' requires a value."
            raise ValueError(msg)
        if op in BINARY_OPERATORS and isinstance(val, list):
            msg = f"Binary operator '{op}' requires a scalar value, not a list."
            raise ValueError(msg)
        return self


class TriggerDefinitionSchema(BaseModel):
    """A single trigger definition within a triggers.json file.

    Defines when a workflow should fire and how webhook payload fields
    map to workflow input variables.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    name: str = Field(
        ...,
        min_length=1,
        description="Human-readable trigger name (e.g., 'on-pr-opened').",
    )
    description: str | None = Field(
        default=None,
        description="What this trigger does and when it fires.",
    )
    event: str = Field(
        ...,
        min_length=1,
        description="GitHub webhook event type (e.g., 'pull_request', 'check_run', 'release'). "
        "See: https://docs.github.com/en/webhooks/webhook-events-and-payloads",
    )
    conditions: list[TriggerConditionSchema] = Field(
        default_factory=list,
        description="Conditions that must ALL match for the trigger to fire. "
        "Empty list means the trigger fires on every event of this type.",
    )
    input_mapping: dict[str, str] = Field(
        default_factory=dict,
        description="Maps workflow input names to dot-notation paths into the webhook payload. "
        "Example: {'pr_number': 'pull_request.number', 'branch': 'pull_request.head.ref'}",
    )


class TriggerFileSchema(BaseModel):
    """Root schema for triggers.json — the distributable trigger definition format.

    Each workflow in a plugin package can include a triggers.json file that
    defines when the workflow should automatically fire in response to GitHub events.
    Triggers are attached to repos at install time via `syn triggers create --from-package`.

    Source of truth for schemas/plugin/triggers.schema.json.
    See ADR-052 for the schema generation strategy.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    triggers: list[TriggerDefinitionSchema] = Field(
        ...,
        min_length=1,
        description="One or more trigger definitions for this workflow.",
    )
