"""CI and the local gate must run the same checks (#931).

The two were assembled from independent lists and drifted: three checks were
reachable from no local recipe at all, the pre-push hook ran only the THRESHOLD
half of fitness, and a stale generated file could reach CI unnoticed. One push
hit three of those at once.

This makes the drift mechanically impossible to reintroduce: any `just` target
CI invokes must be inside `preflight`'s dependency closure.
"""

from __future__ import annotations

import re
import shlex
import shutil
import subprocess
from pathlib import Path

import pytest
from ci.fitness.conftest import AGENT_WORKSPACE_ENV, pytest_runtest_setup

pytestmark = pytest.mark.architecture

_ROOT = Path(__file__).resolve().parents[3]
_JUSTFILE = _ROOT / "justfile"
_WORKFLOWS = _ROOT / ".github" / "workflows"

#: Check-like targets that are deliberately NOT pre-push gates, each with the
#: reason. Anything else matching the naming convention must be in preflight.
#: Targets CI may invoke directly without being a preflight gate.
_ALLOWED_OUTSIDE: dict[str, str] = {
    "codegen": "preflight runs codegen-check, which invokes it and diffs the result",
    "preflight": "the target itself",
    # Skyline (apps/syn-ui) jobs are path-filtered and outside preflight while it
    # is built out at /next; scripts/check_ci_parity.py RUNNABLE_BUT_EXCLUDED
    # records the same split.
    "skyline-ci": "path-filtered Skyline QA (install, test, build, size budget); run by hand",
    "skyline-e2e": "needs a Playwright browser, which a pre-push hook cannot assume",
    "skyline-gateway-smoke": "builds the gateway image, too heavy for a pre-push hook",
}

_NOT_A_GATE: dict[str, str] = {
    "check-fix": "an auto-fixer, not a check",
    "check-version": "release-time only; a feature branch is expected to differ",
    "health-check": "probes a RUNNING stack, which a pre-push hook has no right to assume",
    "import-check": "diagnostic helper, not a gate",
    "topology-check": "regenerated by fitness-check, which preflight already runs",
}


def _direct_deps(target: str, text: str) -> list[str]:
    match = re.search(rf"^{re.escape(target)}:([^\n]*)", text, re.MULTILINE)
    return match.group(1).split() if match else []


def _closure(root: str, text: str) -> set[str]:
    seen: set[str] = set()
    stack = [root]
    while stack:
        current = stack.pop()
        if current in seen:
            continue
        seen.add(current)
        stack.extend(_direct_deps(current, text))
    return seen


def _ci_just_targets() -> set[str]:
    found: set[str] = set()
    for workflow in _WORKFLOWS.glob("*.y*ml"):
        for name in re.findall(r"just ([a-z][a-z0-9:-]*)", workflow.read_text()):
            found.add(name)
    return found


def _declared_checks(text: str) -> set[str]:
    """Every target whose NAME says it is a check."""
    return set(re.findall(r"^(check-[a-z0-9-]+|[a-z0-9-]+-check):", text, re.MULTILINE))


def test_preflight_exists() -> None:
    assert _direct_deps("preflight", _JUSTFILE.read_text()), (
        "`preflight` must exist and name the gates; it is the single list "
        "CI, the pre-push hook and AGENTS.md all point at"
    )


def test_every_ci_check_is_reachable_from_preflight() -> None:
    """CI must not invoke a gate that preflight cannot run.

    Weak on its own now that CI calls `just preflight` rather than naming each
    check - which is the point of that change - so
    ``test_every_declared_check_is_wired_into_preflight`` carries the real
    weight. Kept because CI can always add a direct `just <target>` step again.
    """
    text = _JUSTFILE.read_text()
    covered = _closure("preflight", text)
    missing = sorted(
        t for t in _ci_just_targets() if t not in covered and t not in _ALLOWED_OUTSIDE
    )

    assert not missing, (
        "CI runs `just` targets that `preflight` does not, so they cannot fail "
        f"before a push: {missing}. Add them to `preflight` in the justfile, or "
        "record why they cannot be local gates in _ALLOWED_OUTSIDE."
    )


def test_every_declared_check_is_wired_into_preflight() -> None:
    """A check nobody runs is worse than no check: it reads as coverage.

    This is the invariant that actually bites. Adding `check-foo` to the
    justfile and forgetting to wire it in fails HERE, at the moment the gap is
    created, rather than months later when something slips past it.
    """
    text = _JUSTFILE.read_text()
    covered = _closure("preflight", text)
    orphaned = sorted(
        t for t in _declared_checks(text) if t not in covered and t not in _NOT_A_GATE
    )

    assert not orphaned, (
        f"these checks are defined but nothing runs them before a push: {orphaned}. "
        "Add each to `preflight`, or record in _NOT_A_GATE why it cannot be one."
    )


def test_the_pre_push_hook_delegates_rather_than_listing_its_own_checks() -> None:
    """A hook carrying its own list is how the drift started."""
    hook = _ROOT / ".githooks" / "pre-push"
    if not hook.exists():
        pytest.skip("no pre-push hook in this checkout")
    assert "just preflight" in hook.read_text(), (
        "the pre-push hook must call `just preflight` rather than enumerate checks"
    )


def _body(target: str, text: str) -> str:
    match = re.search(rf"^{re.escape(target)}:[^\n]*\n((?:[ \t]+[^\n]*\n)+)", text, re.MULTILINE)
    return match.group(1) if match else ""


def _commands_run_by(target: str) -> dict[tuple[str, ...], set[tuple[str, str]]]:
    """The argv of every line `just` would execute for ``target``, deps included.

    Read from `just --dry-run`, not from the recipe text, so a line that merely
    MENTIONS a command (``echo just fitness-invariants``) does not count as
    running it. Each argv maps to the env assignments prefixed to it.
    """
    just = shutil.which("just")
    if just is None:
        pytest.fail("`just` is not on PATH; every gate that runs this suite needs it")
    listing = subprocess.run(
        [just, "--dry-run", target],
        cwd=_ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stderr
    commands: dict[tuple[str, ...], set[tuple[str, str]]] = {}
    for line in listing.splitlines():
        try:
            words = shlex.split(line)
        except ValueError:
            continue
        env: set[tuple[str, str]] = set()
        while words and re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*=.*", words[0]):
            name, _, value = words.pop(0).partition("=")
            env.add((name, value))
        if words:
            commands.setdefault(tuple(words), set()).update(env)
    return commands


def test_preflight_agent_runs_both_halves_of_fitness() -> None:
    """Agents gate on `preflight-agent`; it must run ALL of `fitness`.

    `fitness` is two recipes. #1498 wired in `fitness-check` (the APS
    thresholds) and believed fitness was covered; `fitness-invariants`, the
    `pytest ci/fitness` suite, stayed out, and agent PRs went red on CI for
    deep cross-context imports and untyped projection handlers that their
    local gate never ran (#1562). So this follows each half from
    `preflight-agent` down to the command CI's job ends in.

    `preflight` runs `fitness` itself, so it must NOT also reach the agent
    wrappers, or CI would run each half twice.
    """
    text = _JUSTFILE.read_text()
    agent = _closure("preflight-agent", text)

    assert "fitness-agent" in agent, "`preflight-agent` no longer runs fitness-check"
    assert "scripts/agent-fitness.sh" in _body("fitness-agent", text), (
        "`fitness-agent` must run scripts/agent-fitness.sh, which ends in `just fitness-check`"
    )

    assert "fitness-invariants-agent" in agent, (
        "`preflight-agent` no longer runs the `pytest ci/fitness` invariants"
    )
    assert (AGENT_WORKSPACE_ENV, "1") in _commands_run_by("preflight-agent").get(
        ("just", "fitness-invariants"), set()
    ), (
        "`preflight-agent` must EXECUTE `just fitness-invariants` with "
        f"{AGENT_WORKSPACE_ENV}=1: the `fitness-invariants` recipe itself, not a "
        "copy of its command that can drift from CI's"
    )
    pytest_argv = ("uv", "run", "pytest", "ci/fitness/", "-v", "--tb=short", "-m", "architecture")
    assert pytest_argv in _commands_run_by("fitness-invariants"), (
        "`fitness-invariants` no longer runs the CI pytest command"
    )

    full = _closure("preflight", text)
    assert {"fitness-check", "fitness-invariants"} <= full
    assert not {"fitness-agent", "fitness-invariants-agent"} & full, (
        "`preflight` would run a fitness half twice"
    )


def test_only_the_agent_gate_lets_a_missing_host_tool_skip() -> None:
    """The skip switch must not reach CI.

    `preflight` and CI promise docker, so there a `host_tool` test with no
    docker must FAIL. If the variable that turns that into a skip leaked into
    any recipe `preflight` runs, CI would go green over checks it never ran.
    """
    text = _JUSTFILE.read_text()
    setters = {
        target
        for target in re.findall(r"^([a-z][a-z0-9-]*):", text, re.MULTILINE)
        if AGENT_WORKSPACE_ENV in _body(target, text)
    }
    assert setters == {"fitness-invariants-agent"}, setters
    assert not setters & _closure("preflight", text)


class _ItemNeeding:
    """What the skip hook reads from a pytest item: its id and markers."""

    nodeid = "ci/fitness/test_example.py::test_needs_a_tool"

    def __init__(self, tool: str) -> None:
        self._mark = pytest.mark.host_tool(tool).mark

    def iter_markers(self, name: str) -> list[pytest.Mark]:
        return [self._mark] if name == "host_tool" else []


_ABSENT = "syn-no-such-binary-1109"


def test_a_missing_host_tool_skips_as_not_run_in_the_agent_gate(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv(AGENT_WORKSPACE_ENV, "1")
    with pytest.raises(pytest.skip.Exception, match=f"NOT RUN.*{_ItemNeeding.nodeid}.*`{_ABSENT}`"):
        pytest_runtest_setup(_ItemNeeding(_ABSENT))  # type: ignore[arg-type]


def test_a_missing_host_tool_is_not_skipped_anywhere_else(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Under `preflight` and CI the test runs, and fails on the missing binary."""
    monkeypatch.delenv(AGENT_WORKSPACE_ENV, raising=False)
    try:
        pytest_runtest_setup(_ItemNeeding(_ABSENT))  # type: ignore[arg-type]
    except pytest.skip.Exception as skipped:
        # Letting it escape would mark THIS test skipped, green over the very
        # regression it exists to catch.
        pytest.fail(f"a missing host tool skipped outside the agent gate: {skipped}")
