"""CI and the local gate must run the same checks (#931).

The two were assembled from independent lists and drifted: three checks were
reachable from no local recipe at all, the pre-push hook ran only the THRESHOLD
half of fitness, and a stale generated file could reach CI unnoticed. One push
hit three of those at once.

This makes the drift mechanically impossible to reintroduce: any `just` target
CI invokes must be inside `preflight`'s dependency closure.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

pytestmark = pytest.mark.architecture

_ROOT = Path(__file__).resolve().parents[3]
_JUSTFILE = _ROOT / "justfile"
_WORKFLOWS = _ROOT / ".github" / "workflows"

#: Check-like targets that are deliberately NOT pre-push gates, each with the
#: reason. Anything else matching the naming convention must be in preflight.
#: Targets CI may invoke directly without being a preflight gate.
_ALLOWED_OUTSIDE: dict[str, str] = {
    "codegen": "preflight runs codegen-check, which invokes it and diffs the result",
    "preflight": "the target itself",
}

_NOT_A_GATE: dict[str, str] = {
    "check-fix": "an auto-fixer, not a check",
    "check-version": "release-time only; a feature branch is expected to differ",
    "health-check": "probes a RUNNING stack, which a pre-push hook has no right to assume",
    "import-check": "diagnostic helper, not a gate",
    "topology-check": "regenerated by fitness-check, which preflight already runs",
}

def _direct_deps(target: str, text: str) -> list[str]:
    match = re.search(rf"^{re.escape(target)}:([^\n]*)", text, re.MULTILINE)
    return match.group(1).split() if match else []


def _closure(root: str, text: str) -> set[str]:
    seen: set[str] = set()
    stack = [root]
    while stack:
        current = stack.pop()
        if current in seen:
            continue
        seen.add(current)
        stack.extend(_direct_deps(current, text))
    return seen


def _ci_just_targets() -> set[str]:
    found: set[str] = set()
    for workflow in _WORKFLOWS.glob("*.y*ml"):
        for name in re.findall(r"just ([a-z][a-z0-9:-]*)", workflow.read_text()):
            found.add(name)
    return found


def _declared_checks(text: str) -> set[str]:
    """Every target whose NAME says it is a check."""
    return set(re.findall(r"^(check-[a-z0-9-]+|[a-z0-9-]+-check):", text, re.MULTILINE))


def test_preflight_exists() -> None:
    assert _direct_deps("preflight", _JUSTFILE.read_text()), (
        "`preflight` must exist and name the gates; it is the single list "
        "CI, the pre-push hook and AGENTS.md all point at"
    )


def test_every_ci_check_is_reachable_from_preflight() -> None:
    """CI must not invoke a gate that preflight cannot run.

    Weak on its own now that CI calls `just preflight` rather than naming each
    check - which is the point of that change - so
    ``test_every_declared_check_is_wired_into_preflight`` carries the real
    weight. Kept because CI can always add a direct `just <target>` step again.
    """
    text = _JUSTFILE.read_text()
    covered = _closure("preflight", text)
    missing = sorted(
        t for t in _ci_just_targets() if t not in covered and t not in _ALLOWED_OUTSIDE
    )

    assert not missing, (
        "CI runs `just` targets that `preflight` does not, so they cannot fail "
        f"before a push: {missing}. Add them to `preflight` in the justfile, or "
        "record why they cannot be local gates in _ALLOWED_OUTSIDE."
    )


def test_every_declared_check_is_wired_into_preflight() -> None:
    """A check nobody runs is worse than no check: it reads as coverage.

    This is the invariant that actually bites. Adding `check-foo` to the
    justfile and forgetting to wire it in fails HERE, at the moment the gap is
    created, rather than months later when something slips past it.
    """
    text = _JUSTFILE.read_text()
    covered = _closure("preflight", text)
    orphaned = sorted(
        t for t in _declared_checks(text) if t not in covered and t not in _NOT_A_GATE
    )

    assert not orphaned, (
        f"these checks are defined but nothing runs them before a push: {orphaned}. "
        "Add each to `preflight`, or record in _NOT_A_GATE why it cannot be one."
    )


def test_the_pre_push_hook_delegates_rather_than_listing_its_own_checks() -> None:
    """A hook carrying its own list is how the drift started."""
    hook = _ROOT / ".githooks" / "pre-push"
    if not hook.exists():
        pytest.skip("no pre-push hook in this checkout")
    assert "just preflight" in hook.read_text(), (
        "the pre-push hook must call `just preflight` rather than enumerate checks"
    )
