"""Every package that generates API types must be generated by `just codegen` (#1182).

`codegen-check` detects drift by running `just codegen` and diffing what it
CHANGED. That is blind to a package the recipe never visits: `packages/
openclaw-plugin` shipped hand-written response interfaces for months, went a
schema behind when `/executions` grew `status_counts`, and no gate could see
it, because "not regenerated" produces no diff to notice.

So the property is coverage, not freshness: if a workspace package declares a
`generate:types` script, the `codegen` recipe must invoke it. Wire up the
fifth consumer and forget the recipe line, and this fails at preflight rather
than the next time someone reads the types by hand.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest
import yaml

pytestmark = pytest.mark.architecture

_ROOT = Path(__file__).resolve().parents[3]
_JUSTFILE = _ROOT / "justfile"
_WORKSPACE = _ROOT / "pnpm-workspace.yaml"

#: The script name every generated-types package exposes, by convention.
_GENERATE_SCRIPT = "generate:types"


def _workspace_packages() -> list[Path]:
    """Workspace member directories, as pnpm resolves them."""
    globs: list[str] = yaml.safe_load(_WORKSPACE.read_text())["packages"]
    found: list[Path] = []
    for pattern in globs:
        found.extend(sorted(p for p in _ROOT.glob(pattern) if (p / "package.json").is_file()))
    return found


def _recipe_body(target: str) -> str:
    """The lines of a just recipe: its header line plus the indented block."""
    text = _JUSTFILE.read_text()
    match = re.search(rf"^{re.escape(target)}:.*?(?=^\S|\Z)", text, re.MULTILINE | re.DOTALL)
    assert match is not None, f"justfile has no `{target}` recipe"
    return match.group(0)


def _packages_generating_types() -> list[Path]:
    generating: list[Path] = []
    for package in _workspace_packages():
        manifest = json.loads((package / "package.json").read_text())
        if _GENERATE_SCRIPT in manifest.get("scripts", {}):
            generating.append(package)
    return generating


def test_every_generating_package_is_reachable_from_codegen() -> None:
    body = _recipe_body("codegen")
    missing = [
        package.relative_to(_ROOT).as_posix()
        for package in _packages_generating_types()
        if package.relative_to(_ROOT).as_posix() not in body
    ]
    assert not missing, (
        f"`just codegen` never visits {missing}, so their generated types can go "
        f"stale without producing a diff for codegen-check to catch. Add a "
        f"`cd <package> && pnpm run {_GENERATE_SCRIPT}` step to the codegen recipe."
    )


def test_the_known_generated_clients_are_all_present() -> None:
    """Pins the check against its own blind spot.

    `test_every_generating_package_is_reachable_from_codegen` passes vacuously
    if `_packages_generating_types()` returns nothing -- which is exactly what
    a broken workspace glob or a renamed script key would produce, and it would
    pass green forever. Naming the consumers costs one line per package added.
    """
    found = {package.relative_to(_ROOT).as_posix() for package in _packages_generating_types()}
    assert found == {
        "apps/syn-cli-node",
        "apps/syn-dashboard-ui",
        "packages/openclaw-plugin",
    }, f"generated-types consumers changed: {sorted(found)}"
