#!/usr/bin/env python3
"""Generate docker-compose.syntropic137.yaml from base + selfhost overlays.

Merges docker/docker-compose.yaml and docker/docker-compose.selfhost.yaml,
then applies transformations for standalone deployment:
  - build: blocks → image: references (GHCR)
  - Secret/volume paths → relative to ~/.syntropic137/
  - Hardcoded project name and selfhost-specific defaults

Usage:
    python scripts/generate_published_compose.py          # Write file
    python scripts/generate_published_compose.py --check   # CI: fail if stale
    just gen-compose                                       # Shortcut
    just check-compose                                     # CI shortcut
"""

from __future__ import annotations

import argparse
import copy
import re
import sys
from io import StringIO
from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).parent.parent
DOCKER_DIR = PROJECT_ROOT / "docker"
BASE_COMPOSE = DOCKER_DIR / "docker-compose.yaml"
SELFHOST_COMPOSE = DOCKER_DIR / "docker-compose.selfhost.yaml"
CLOUDFLARE_COMPOSE = DOCKER_DIR / "docker-compose.cloudflare.yaml"
OUTPUT_FILE = DOCKER_DIR / "docker-compose.syntropic137.yaml"

# ---------------------------------------------------------------------------
# Service name → GHCR image reference
# Services not listed keep their original `image:` from the source files.
# ---------------------------------------------------------------------------
SERVICE_IMAGES: dict[str, str] = {
    "event-store": "ghcr.io/syntropic137/event-store",
    "collector": "ghcr.io/syntropic137/syn-collector",
    "api": "ghcr.io/syntropic137/syn-api",
    "gateway": "ghcr.io/syntropic137/syn-gateway",
    "envoy-proxy": "ghcr.io/syntropic137/sidecar-proxy",
    "token-injector": "ghcr.io/syntropic137/token-injector",
}

# Service order in the output (readability — matches current published file)
SERVICE_ORDER = [
    "timescaledb",
    "event-store",
    "collector",
    "docker-socket-proxy",
    "api",
    "gateway",
    "cloudflared",
    "minio",
    "redis",
    "envoy-proxy",
    "token-injector",
]

FILE_HEADER = """\
# =============================================================================
# Syntropic137 — Self-Host Docker Compose (Published)
# =============================================================================
#
# AUTO-GENERATED by scripts/generate_published_compose.py
# Inputs: docker-compose.yaml + docker-compose.selfhost.yaml
# Regenerate: just gen-compose
#
# This is a SELF-CONTAINED compose file for self-hosters who pull pre-built
# images from GHCR. No source code or submodules required.
#
# Setup:
#   1. Copy this file to ~/.syntropic137/
#   2. Copy selfhost-entrypoint.sh to ~/.syntropic137/
#   3. Copy .env.example to ~/.syntropic137/.env and configure
#   4. Create secrets: mkdir -p secrets/ && openssl rand -hex 32 > secrets/db-password.secret
#   5. docker compose -f docker-compose.syntropic137.yaml up -d
#
# See: https://docs.syntropic137.dev/self-host
# =============================================================================

"""


# =============================================================================
# YAML helpers
# =============================================================================


def _env_to_dict(env: dict | list | None) -> dict[str, str]:
    """Normalize environment (list or dict form) to dict."""
    if env is None:
        return {}
    if isinstance(env, dict):
        return {str(k): str(v) if v is not None else "" for k, v in env.items()}
    result: dict[str, str] = {}
    for item in env:
        s = str(item)
        if "=" in s:
            k, _, v = s.partition("=")
            result[k] = v
        else:
            result[s] = ""
    return result


def _deep_merge(base: dict, overlay: dict) -> dict:
    """Deep merge overlay into base (overlay wins for scalars/lists)."""
    result = copy.deepcopy(base)
    for k, v in overlay.items():
        if k in result and isinstance(result[k], dict) and isinstance(v, dict):
            result[k] = _deep_merge(result[k], v)
        else:
            result[k] = copy.deepcopy(v)
    return result


def _merge_service(base_svc: dict, overlay_svc: dict) -> dict:
    """Merge a base service with its overlay, normalizing environment."""
    base_env = _env_to_dict(base_svc.get("environment"))
    overlay_env = _env_to_dict(overlay_svc.get("environment"))

    merged = _deep_merge(base_svc, overlay_svc)

    # Environment: per-key merge (overlay wins)
    merged_env = {**base_env, **overlay_env}
    if merged_env:
        merged["environment"] = merged_env

    return merged


# =============================================================================
# Publish-specific transforms
# =============================================================================
# These transforms convert a base+selfhost merge into the standalone published
# compose that self-hosters download. Each is documented with WHY it exists.
# =============================================================================


def _replace_builds_with_images(services: dict) -> None:
    """Replace build: blocks with GHCR image: references.

    Published compose uses pre-built images — no source code needed.
    """
    for name, svc in services.items():
        if name in SERVICE_IMAGES:
            svc.pop("build", None)
            svc["image"] = f"{SERVICE_IMAGES[name]}:${{SYN_VERSION:-latest}}"


def _rewrite_paths(services: dict) -> None:
    """Rewrite volume/path mounts for standalone ~/.syntropic137/ layout.

    In-repo paths (../workspaces, ../infra/docker/secrets/) become relative
    to the self-hoster's installation directory.
    """
    for svc in services.values():
        volumes = svc.get("volumes")
        if not volumes:
            continue
        rewritten = []
        for v in volumes:
            if isinstance(v, str):
                v = v.replace("../workspaces", "./workspaces")
            rewritten.append(v)
        svc["volumes"] = rewritten


def _replace_default_network(services: dict) -> None:
    """Replace 'default' network with 'syn-internal' for explicit networking.

    Base compose uses the implicit 'default' network. Published compose is
    explicit about all networking — 'default' → 'syn-internal'.
    """
    for svc in services.values():
        networks = svc.get("networks")
        if networks and isinstance(networks, list):
            svc["networks"] = ["syn-internal" if n == "default" else n for n in networks]


def _apply_api_overrides(services: dict) -> None:
    """Apply API service overrides for standalone selfhost deployment.

    - APP_ENVIRONMENT defaults to 'selfhost' (not 'production')
    - SYN_AGENT_NETWORK is hardcoded (project name is fixed)
    - GitHub App PEM uses file-based Docker secret (not env var)
    """
    if "api" not in services:
        return
    env = services["api"].get("environment", {})
    env["APP_ENVIRONMENT"] = "${APP_ENVIRONMENT:-selfhost}"
    env["SYN_AGENT_NETWORK"] = "syntropic137_selfhost_agent-net"
    # File-based secret replaces direct env var for PEM
    env["SYN_GITHUB_APP_PRIVATE_KEY_FILE"] = "/run/secrets/github_app_private_key"
    env.pop("SYN_GITHUB_PRIVATE_KEY", None)
    services["api"]["environment"] = env

    # Ensure github_app_private_key in secrets list
    secrets = services["api"].get("secrets", [])
    if "github_app_private_key" not in secrets:
        secrets.append("github_app_private_key")
    services["api"]["secrets"] = secrets


def _apply_envoy_overrides(services: dict) -> None:
    """Apply selfhost hardening and TCP healthcheck for envoy-proxy.

    envoy-proxy and token-injector are only defined in the base compose
    (no selfhost overlay). The published compose needs container_name,
    restart policy, explicit networks, and a TCP healthcheck (the published
    sidecar-proxy image may not include curl).
    """
    if "envoy-proxy" in services:
        svc = services["envoy-proxy"]
        svc["container_name"] = "syn137-envoy-proxy"
        svc["restart"] = "always"
        svc["networks"] = ["syn-internal", "agent-net"]
        svc["healthcheck"] = {
            "test": ["CMD-SHELL", "bash -c '</dev/tcp/localhost/8081' || exit 1"],
            "interval": "10s",
            "timeout": "5s",
            "retries": 3,
            "start_period": "5s",
        }

    if "token-injector" in services:
        svc = services["token-injector"]
        svc["container_name"] = "syn137-token-injector"
        svc["restart"] = "always"
        svc["networks"] = ["syn-internal"]


def _apply_collector_overrides(services: dict) -> None:
    """Ensure collector has entrypoint/command for secret injection.

    The selfhost overlay adds the selfhost-entrypoint.sh for secret
    injection (reads db_password Docker secret into SYN_OBSERVABILITY_DB_URL).
    This function is idempotent — it ensures the published compose has
    the same configuration.
    """
    if "collector" not in services:
        return
    svc = services["collector"]
    # Mount entrypoint script
    volumes = svc.get("volumes", [])
    if not any("selfhost-entrypoint" in str(v) for v in volumes):
        volumes.append("./selfhost-entrypoint.sh:/selfhost-entrypoint.sh:ro")
    svc["volumes"] = volumes
    svc["entrypoint"] = ["/bin/sh", "/selfhost-entrypoint.sh"]
    svc["command"] = [
        "python",
        "-m",
        "syn_collector.cli",
        "serve",
        "--port",
        "8080",
        "--host",
        "0.0.0.0",
    ]
    # Add db_password secret
    secrets = svc.get("secrets", [])
    if "db_password" not in secrets:
        secrets.append("db_password")
    svc["secrets"] = secrets


def _add_cloudflared(services: dict) -> None:
    """Add cloudflared service from the cloudflare overlay.

    The cloudflare overlay (docker-compose.cloudflare.yaml) defines a
    standalone tunnel service. For the published compose, we include it
    with profiles: [tunnel] so it only starts when explicitly enabled,
    plus security hardening consistent with other selfhost services.
    """
    if "cloudflared" in services:
        return  # Already present (e.g., if selfhost overlay is updated later)

    cf = yaml.safe_load(CLOUDFLARE_COMPOSE.read_text())
    cf_svc = (cf.get("services", {}) or {}).get("cloudflared")
    if not cf_svc:
        return

    # Start from the overlay definition, then harden for published use
    svc = copy.deepcopy(cf_svc)
    svc["container_name"] = "syn137-cloudflared"
    svc["profiles"] = ["tunnel"]
    # Only depend on gateway — api is a transitive dependency
    svc["depends_on"] = {"gateway": {"condition": "service_healthy"}}
    # Normalize env var to use :- default syntax
    env = _env_to_dict(svc.get("environment"))
    env["TUNNEL_TOKEN"] = "${CLOUDFLARE_TUNNEL_TOKEN:-}"
    svc["environment"] = env
    # Security hardening
    svc["restart"] = "on-failure:3"
    svc["read_only"] = True
    svc["security_opt"] = ["no-new-privileges:true"]
    svc["cap_drop"] = ["ALL"]
    svc["deploy"] = {"resources": {"limits": {"memory": "128m", "cpus": "0.25"}}}
    svc["logging"] = {
        "driver": "json-file",
        "options": {"max-size": "10m", "max-file": "3"},
    }
    svc["networks"] = ["syn-internal"]

    services["cloudflared"] = svc


def _rewrite_secrets(secrets: dict) -> dict:
    """Rewrite secret file paths for standalone layout.

    In-repo: ../infra/docker/secrets/foo.secret
    Published: ./secrets/foo.secret
    """
    result: dict[str, dict] = {}
    for name, defn in secrets.items():
        if isinstance(defn, dict) and "file" in defn:
            path = defn["file"].replace("../infra/docker/secrets/", "./secrets/")
            result[name] = {"file": path}
        else:
            result[name] = copy.deepcopy(defn)

    # Ensure github_app_private_key secret exists
    if "github_app_private_key" not in result:
        result["github_app_private_key"] = {
            "file": "./secrets/github-app-private-key.pem",
        }
    return result


# =============================================================================
# Generation
# =============================================================================


def generate() -> dict:
    """Generate the published compose as a Python dict."""
    base = yaml.safe_load(BASE_COMPOSE.read_text())
    selfhost = yaml.safe_load(SELFHOST_COMPOSE.read_text())

    base_svcs = base.get("services", {})
    selfhost_svcs = selfhost.get("services", {})

    # Merge services (base + selfhost overlay)
    all_names = set(base_svcs) | set(selfhost_svcs)
    merged_svcs: dict = {}
    for name in all_names:
        b = base_svcs.get(name, {})
        o = selfhost_svcs.get(name, {})
        if b and o:
            merged_svcs[name] = _merge_service(b, o)
        elif b:
            merged_svcs[name] = copy.deepcopy(b)
        else:
            merged_svcs[name] = copy.deepcopy(o)

    # Apply transforms
    _replace_builds_with_images(merged_svcs)
    _rewrite_paths(merged_svcs)
    _replace_default_network(merged_svcs)
    _apply_api_overrides(merged_svcs)
    _apply_envoy_overrides(merged_svcs)
    _apply_collector_overrides(merged_svcs)
    _add_cloudflared(merged_svcs)

    # Gateway environment: selfhost overlay uses list form, normalize to dict
    if "gateway" in merged_svcs:
        env = _env_to_dict(merged_svcs["gateway"].get("environment"))
        if env:
            merged_svcs["gateway"]["environment"] = env

    # Order services
    ordered_svcs: dict = {}
    for name in SERVICE_ORDER:
        if name in merged_svcs:
            ordered_svcs[name] = merged_svcs[name]
    for name in merged_svcs:
        if name not in ordered_svcs:
            ordered_svcs[name] = merged_svcs[name]

    # Merge secrets
    base_secrets = base.get("secrets", {}) or {}
    selfhost_secrets = selfhost.get("secrets", {}) or {}
    merged_secrets = _rewrite_secrets({**base_secrets, **selfhost_secrets})

    # Merge networks (selfhost defines syn-internal/syn-proxy, base defines agent-net)
    base_nets = base.get("networks", {}) or {}
    selfhost_nets = selfhost.get("networks", {}) or {}
    merged_nets = {**selfhost_nets, **base_nets}
    # selfhost networks first, then base (agent-net)

    # Volumes from selfhost
    volumes = selfhost.get("volumes", {}) or {}

    return {
        "name": "syntropic137_selfhost",
        "services": ordered_svcs,
        "secrets": merged_secrets,
        "volumes": volumes,
        "networks": merged_nets,
    }


# =============================================================================
# Custom YAML output
# =============================================================================


class _ComposeDumper(yaml.SafeDumper):
    """YAML dumper tuned for Docker Compose files."""


def _str_representer(dumper: _ComposeDumper, data: str) -> yaml.ScalarNode:
    """Represent strings with minimal quoting for Docker Compose conventions."""
    if not data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style='"')
    if "\n" in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    # Force quotes for values YAML would misinterpret
    if data.lower() in {"true", "false", "yes", "no", "on", "off", "null", "~"}:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style='"')
    # Quote pure numbers (Docker Compose env values like "8080" need quotes)
    try:
        float(data.replace(":", "").replace(",", ""))
        if data.replace(".", "").replace("-", "").isdigit() or data in ("0.0.0.0",):
            return dumper.represent_scalar("tag:yaml.org,2002:str", data, style='"')
    except ValueError:
        pass
    # Default: let PyYAML choose (it will quote if needed for YAML safety)
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


_ComposeDumper.add_representer(str, _str_representer)


def _postprocess(text: str) -> str:
    """Clean up PyYAML output to match Docker Compose conventions."""
    # PyYAML single-quotes strings with ${} — remove those quotes.
    # Pattern: key: '...${...}...' → key: ...${...}...
    text = re.sub(r"(?<=: )'([^']*\$\{[^']*}[^']*)'", r"\1", text)

    # Also handle double-quoted ${} patterns
    text = re.sub(r'(?<=: )"([^"]*\$\{[^"]*}[^"]*)"', r"\1", text)

    # Remove quotes from simple path values: './foo', '../foo'
    text = re.sub(r"(?<=: )'(\./[^']*)'", r"\1", text)

    return text


def render(data: dict) -> str:
    """Render the compose dict to a YAML string with header."""
    stream = StringIO()
    yaml.dump(
        data,
        stream,
        Dumper=_ComposeDumper,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
        width=120,
    )
    yaml_text = _postprocess(stream.getvalue())
    return FILE_HEADER + yaml_text


# =============================================================================
# Normalization for --check comparison
# =============================================================================


def _normalize(data: object) -> object:
    """Normalize a parsed YAML structure for comparison.

    Handles type coercion differences (int vs str in env values, etc.).
    """
    if isinstance(data, dict):
        return {str(k): _normalize(v) for k, v in data.items()}
    if isinstance(data, list):
        return [_normalize(item) for item in data]
    if data is None:
        return None
    return data


# =============================================================================
# Main
# =============================================================================


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate published Docker Compose for self-hosters",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check committed file matches generated (CI mode)",
    )
    args = parser.parse_args()

    data = generate()

    if args.check:
        if not OUTPUT_FILE.exists():
            print(
                f"ERROR: {OUTPUT_FILE.relative_to(PROJECT_ROOT)} does not exist",
                file=sys.stderr,
            )
            sys.exit(1)
        committed_data = yaml.safe_load(OUTPUT_FILE.read_text())
        if _normalize(committed_data) == _normalize(data):
            print(f"OK: {OUTPUT_FILE.name} is up to date")
            sys.exit(0)

        # Show what diverged
        print(
            f"ERROR: {OUTPUT_FILE.name} is out of sync with source compose files",
            file=sys.stderr,
        )
        _show_diff(committed_data, data)
        print("\nRun: just gen-compose", file=sys.stderr)
        sys.exit(1)
    else:
        output = render(data)
        OUTPUT_FILE.write_text(output)
        print(f"Generated: {OUTPUT_FILE.relative_to(PROJECT_ROOT)}")


def _show_diff(committed: object, generated: object, path: str = "") -> None:
    """Print structural differences between committed and generated."""
    if type(committed) is not type(generated):
        print(f"  {path}: type mismatch ({type(committed).__name__} vs {type(generated).__name__})")
        return
    if isinstance(committed, dict) and isinstance(generated, dict):
        all_keys = set(committed) | set(generated)
        for key in sorted(all_keys):
            child_path = f"{path}.{key}" if path else key
            if key not in committed:
                print(f"  + {child_path} (missing in committed)")
            elif key not in generated:
                print(f"  - {child_path} (extra in committed)")
            elif _normalize(committed[key]) != _normalize(generated[key]):
                _show_diff(committed[key], generated[key], child_path)
    elif isinstance(committed, list):
        if _normalize(committed) != _normalize(generated):
            print(f"  {path}: list differs")
    elif str(committed) != str(generated):
        print(f"  {path}: {committed!r} → {generated!r}")


if __name__ == "__main__":
    main()
