"""The host side of reclaiming workspace directories whose container is gone (PC-130).

Three things the domain guard (`guard_stale_workspace_dir`) cannot do itself:
see which directories exist and which containers still mount them, read their
repositories with git from the host, and archive a dirty tree to MinIO.

RUNNING GIT ON A REPOSITORY AN AGENT WROTE. The repository's own config is
the agent's to write, and git runs commands named there (filters, diff
drivers, fsmonitor). This process is the API, on the host. So a repository
whose config names a command is never read here - it is reported unreadable,
which keeps the directory - and every call disables the remaining hooks.
The config is listed under the same trust (`safe.directory=*`) as every later
call: listed without it, git silently drops a different owner's repository
config, the scan sees nothing, and the next call loads and runs it.

WHAT A REPOSITORY DOES NOT HOLD. A workspace keeps work outside its working
trees too - `artifacts/output`, session spools, a bare clone, a stash, a file
the repository ignores. Bare repositories are guarded like any other; every
other file git cannot reproduce is archived as one tarball, and only proven
caches (`_DISPOSABLE_DIRS`) are left out of it.
"""

from __future__ import annotations

import asyncio
import hashlib
import io
import os
import tarfile
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

from syn_adapters.workspace_backends.orphaned import docker_inspect_raw, parse_inspect

if TYPE_CHECKING:
    from syn_domain.contexts.orchestration import StaleWorkspaceDir

#: A patch larger than this is not archived, so its directory is kept: a
#: tree that big is not "a few uncommitted edits", and an operator decides.
MAX_PATCH_BYTES = 100 * 1024 * 1024

#: Config keys whose value git may execute. A repository setting any of them
#: is not read from the host at all.
_COMMAND_KEY_SUFFIXES = (
    ".clean",
    ".smudge",
    ".process",
    ".command",
    ".textconv",
    "core.fsmonitor",
    "core.pager",
    "core.sshcommand",
    "core.gitproxy",
    "core.askpass",
    "core.editor",
    "core.hookspath",
    "gpg.program",
    "credential.helper",
)

_GIT_GUARD_ARGS = (
    "-c",
    "safe.directory=*",
    "-c",
    "core.fsmonitor=false",
    "-c",
    "core.hooksPath=/dev/null",
)

#: Only `safe.directory`: the config listing must see what later calls load,
#: without echoing our own command-disabling overrides back as findings.
_GIT_TRUST_ARGS = ("-c", "safe.directory=*")

#: Directory names whose contents are regenerated by a build or install, so
#: losing them loses no authored work. Anything else unversioned is archived.
_DISPOSABLE_DIRS = frozenset(
    {
        "node_modules",
        ".venv",
        "__pycache__",
        ".pytest_cache",
        ".mypy_cache",
        ".ruff_cache",
        ".cache",
        "target",
    }
)

_GIT_TIMEOUT_SECONDS = 120


class HostGitError(RuntimeError):
    """Git could not give a definite answer about a repository."""


@dataclass(frozen=True)
class WorkspaceDirListing:
    """One directory under the workspace base, measured in a single walk."""

    workspace_id: str
    host_dir: str
    size_bytes: int
    #: Newest mtime of anything inside, epoch seconds: the grace clock.
    last_modified: float


@dataclass(frozen=True)
class WorkspaceContainer:
    """A workspace container in any state, by the directory it mounts."""

    workspace_id: str
    execution_id: str | None
    running: bool


def scan_workspace_dirs(base: str) -> list[WorkspaceDirListing]:
    """Every directory directly under ``base``, sized. Blocking: call off the loop."""
    root = Path(base)
    if not root.is_dir():
        return []
    listings: list[WorkspaceDirListing] = []
    for entry in sorted(root.iterdir()):
        if entry.is_dir() and not entry.is_symlink():
            size, newest = _measure(entry)
            listings.append(
                WorkspaceDirListing(
                    workspace_id=entry.name,
                    host_dir=str(entry),
                    size_bytes=size,
                    last_modified=newest,
                )
            )
    return listings


def _measure(directory: Path) -> tuple[int, float]:
    size = 0
    newest = directory.lstat().st_mtime
    for dirpath, dirnames, filenames in os.walk(directory):
        here = Path(dirpath)
        # Git's own bookkeeping is not work: reading a repository refreshes
        # its index, and that must not read as "changed during archival".
        # A commit made in there is caught by the unpushed guard instead.
        bookkeeping = ".git" in here.relative_to(directory).parts
        for name, is_file in (*((d, False) for d in dirnames), *((f, True) for f in filenames)):
            try:
                stat = (here / name).lstat()
            except OSError:
                continue
            if not bookkeeping and name != ".git":
                newest = max(newest, stat.st_mtime)
            if is_file:
                size += stat.st_size
    return size, newest


async def list_workspace_containers() -> list[WorkspaceContainer]:
    """Every ``agentic-ws-`` container, stopped ones included.

    Raises when any of them cannot be read: a container whose state is unknown
    may be running, and its directory must then be left alone.
    """
    proc = await asyncio.create_subprocess_exec(
        "docker",
        "ps",
        "-a",
        "-q",
        "--filter",
        "name=agentic-ws-",
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.DEVNULL,
    )
    stdout, _ = await asyncio.wait_for(proc.communicate(), timeout=10)
    if proc.returncode != 0:
        raise RuntimeError(f"docker ps -a exited {proc.returncode}")
    containers: list[WorkspaceContainer] = []
    for container_id in stdout.decode().split():
        raw = await docker_inspect_raw(container_id)
        inspected = parse_inspect(raw) if raw is not None else None
        if inspected is None:
            raise RuntimeError(f"could not inspect workspace container {container_id}")
        if inspected.workspace_source is None:
            continue
        containers.append(
            WorkspaceContainer(
                workspace_id=Path(inspected.workspace_source).name,
                execution_id=inspected.labels.get("syn.execution_id") or None,
                running=inspected.running,
            )
        )
    return containers


class SubprocessHostWorkspaceGit:
    """`HostWorkspaceGit` over the host's ``git`` binary."""

    async def repositories(self, host_dir: str) -> list[str]:
        return await asyncio.to_thread(_find_repositories, host_dir)

    async def unpushed_commits(self, repo: str) -> int:
        await self._refuse_command_config(repo)
        # Every ref (branches, tags, stash) and HEAD: an agent on a detached
        # HEAD commits too, and a stash is work no branch reaches.
        out = await _git(repo, "rev-list", "--count", "--all", "HEAD", "--not", "--remotes")
        return int(out.strip() or b"0")

    async def uncommitted_patch(self, repo: str) -> bytes:
        await self._refuse_command_config(repo)
        if _is_bare(repo):
            return b""
        diff_args = ("--binary", "--no-ext-diff", "--no-textconv", "--no-color")
        # A HEAD-to-tree patch holds one state. When the index differs from
        # both HEAD and the tree, the staged state would be lost: keep it.
        staged = await _git(repo, "diff", "--cached", "--quiet", ok_codes=(0, 1), status=True)
        unstaged = await _git(repo, "diff", "--quiet", ok_codes=(0, 1), status=True)
        if staged and unstaged:
            raise HostGitError(f"{repo} has staged changes the working tree no longer matches")
        patch = await _git(repo, "diff", *diff_args, "HEAD")
        untracked = await _git(repo, "ls-files", "--others", "--exclude-standard", "-z")
        for name in filter(None, untracked.decode(errors="surrogateescape").split("\0")):
            # Exit 1 is "they differ", which for /dev/null is always.
            patch += await _git(
                repo, "diff", "--no-index", *diff_args, "--", "/dev/null", name, ok_codes=(0, 1)
            )
            if len(patch) > MAX_PATCH_BYTES:
                raise HostGitError(f"uncommitted changes in {repo} exceed {MAX_PATCH_BYTES} bytes")
        if len(patch) > MAX_PATCH_BYTES:
            raise HostGitError(f"uncommitted changes in {repo} exceed {MAX_PATCH_BYTES} bytes")
        return patch

    async def unversioned_files(self, host_dir: str, repos: list[str]) -> bytes:
        ignored: list[str] = []
        for repo in repos:
            if _is_bare(repo):
                continue
            await self._refuse_command_config(repo)
            out = await _git(
                repo, "ls-files", "--others", "--ignored", "--exclude-standard", "--directory", "-z"
            )
            ignored.extend(
                str(Path(repo) / name.rstrip("/"))
                for name in out.decode(errors="surrogateescape").split("\0")
                if name
            )
        return await asyncio.to_thread(_tar_unversioned, host_dir, repos, ignored)

    async def _refuse_command_config(self, repo: str) -> None:
        # Under the trust later calls use, but without our command-disabling
        # overrides, which `--list` would report back.
        config = await _git(
            repo, "config", "--list", "--name-only", "-z", overrides=_GIT_TRUST_ARGS
        )
        for key in filter(None, config.decode(errors="replace").lower().split("\0")):
            if key.endswith(_COMMAND_KEY_SUFFIXES):
                raise HostGitError(f"{repo} configures a command ({key}); not run from the host")


def _find_repositories(host_dir: str) -> list[str]:
    repos: list[str] = []
    for dirpath, dirnames, filenames in os.walk(host_dir):
        if _looks_bare(dirpath, dirnames, filenames):
            # A bare clone holds refs no working tree shows; guard it, and do
            # not walk into its object store.
            repos.append(dirpath)
            dirnames.clear()
            continue
        if ".git" in dirnames or ".git" in filenames:
            repos.append(dirpath)
        if ".git" in dirnames:
            dirnames.remove(".git")
    return repos


def _looks_bare(dirpath: str, dirnames: list[str], filenames: list[str]) -> bool:
    return (
        "HEAD" in filenames
        and "objects" in dirnames
        and "refs" in dirnames
        and Path(dirpath).name != ".git"
    )


def _is_bare(repo: str) -> bool:
    return not (Path(repo) / ".git").exists()


def _tar_unversioned(host_dir: str, repos: list[str], ignored: list[str]) -> bytes:
    """A gzipped tar of what git cannot reproduce, or b"" when there is none.

    Everything outside every repository, plus each repository's ignored files,
    less `_DISPOSABLE_DIRS`. Raises `HostGitError` past `MAX_PATCH_BYTES`.
    """
    root = Path(host_dir)
    repo_roots = {Path(r) for r in repos}
    members = _unversioned_under(root, repo_roots)
    for name in ignored:
        path = Path(name)
        if not any(part in _DISPOSABLE_DIRS for part in path.relative_to(root).parts):
            members.extend(_unversioned_under(path, repo_roots))
    if not members:
        return b""
    return _write_tar(root, sorted(set(members)))


def _unversioned_under(path: Path, repo_roots: set[Path]) -> list[Path]:
    """``path`` itself if a file, else every file below it outside ``repo_roots`` and caches."""
    if path.is_symlink() or path.is_file():
        return [path]
    members: list[Path] = []
    for dirpath, dirnames, filenames in os.walk(path):
        here = Path(dirpath)
        dirnames[:] = [
            d for d in dirnames if d not in _DISPOSABLE_DIRS and here / d not in repo_roots
        ]
        members.extend(here / f for f in filenames)
        members.extend(here / d for d in dirnames if (here / d).is_symlink())
    return members


def _write_tar(root: Path, members: list[Path]) -> bytes:
    total = 0
    buffer = io.BytesIO()
    with tarfile.open(fileobj=buffer, mode="w:gz") as tar:
        for member in members:
            total += member.lstat().st_size
            if total > MAX_PATCH_BYTES:
                raise HostGitError(f"unversioned files in {root} exceed {MAX_PATCH_BYTES} bytes")
            tar.add(member, arcname=str(member.relative_to(root)), recursive=False)
    return buffer.getvalue()


async def _git(
    repo: str,
    *args: str,
    ok_codes: tuple[int, ...] = (0,),
    overrides: tuple[str, ...] = _GIT_GUARD_ARGS,
    status: bool = False,
) -> bytes:
    """Stdout, or with ``status`` b"1" when git exited non-zero and b"" when zero."""
    env = {
        "PATH": os.environ.get("PATH", "/usr/bin:/bin"),
        "HOME": "/nonexistent",
        "GIT_CONFIG_NOSYSTEM": "1",
        "GIT_CONFIG_GLOBAL": "/dev/null",
        "GIT_TERMINAL_PROMPT": "0",
        "GIT_OPTIONAL_LOCKS": "0",
    }
    proc = await asyncio.create_subprocess_exec(
        "git",
        *overrides,
        "-C",
        repo,
        *args,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
        stdin=asyncio.subprocess.DEVNULL,
        env=env,
    )
    try:
        stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=_GIT_TIMEOUT_SECONDS)
    except TimeoutError:
        proc.kill()
        await proc.wait()
        raise HostGitError(f"git {args[0]} timed out in {repo}") from None
    if proc.returncode not in ok_codes:
        raise HostGitError(
            f"git {args[0]} exited {proc.returncode} in {repo}: "
            f"{stderr.decode(errors='replace')[:300].strip()}"
        )
    if status:
        return b"1" if proc.returncode else b""
    return stdout


def archive_key(stale: StaleWorkspaceDir, path: str) -> str:
    """A key unique per (workspace, path): readable slug plus a hash of the exact path.

    The slug alone is not injective (``a_b`` and ``a/b`` meet), and an object
    store overwrites on a repeated key.
    """
    relative = str(Path(path).relative_to(stale.host_dir))
    slug = relative.replace(os.sep, "_").strip("._") or "root"
    digest = hashlib.sha256(relative.encode(errors="surrogateescape")).hexdigest()[:16]
    return f"reclaimed-{stale.workspace_id}-{slug}-{digest}"


class ArtifactStoragePatchArchive:
    """`PatchArchive` over the artifact bucket, keyed under the execution."""

    async def save(self, stale: StaleWorkspaceDir, repo: str, patch: bytes) -> str:
        from syn_adapters.storage.artifact_storage.factory import get_artifact_storage

        storage = await get_artifact_storage()
        result = await storage.upload(
            archive_key(stale, repo),
            patch,
            execution_id=stale.execution_id,
            content_type="text/x-diff",
            metadata={"reclaimed_from": stale.host_dir, "repository": repo},
        )
        return result.storage_uri

    async def save_files(self, stale: StaleWorkspaceDir, tarball: bytes) -> str:
        from syn_adapters.storage.artifact_storage.factory import get_artifact_storage

        storage = await get_artifact_storage()
        result = await storage.upload(
            f"{archive_key(stale, stale.host_dir)}-files",
            tarball,
            execution_id=stale.execution_id,
            content_type="application/gzip",
            metadata={"reclaimed_from": stale.host_dir},
        )
        return result.storage_uri
